#+TITLE: [[file:index.html][=stephen=]] \\
#+AUTHOR:    Stephen Maxwell
#+OPTIONS: whn:nil
#+LINK_HOME: http://stephenmaxwell.me

* Learning hiragana
/05-05-2014/

* What is it

I have been learning [[https://en.wikipedia.org/wiki/Hiragana][hiragana]], one of the alphabets used in the Japanese language. More specifically, it 
is one of two Japanese syllabaries.

There are four main components to the Japanese writing system: hiragana, 
[[https://en.wikipedia.org/wiki/Katakana][katakana]], [[https://en.wikipedia.org/wiki/Kanji][kanji]] 
and [[https://en.wikipedia.org/wiki/Romanization_of_Japanese][romanji]] (Latin script). 
Hiragana and katakana (the two [[https://en.wikipedia.org/wiki/Kana][kana]]) are both syllabic systems, whereas kanji is [[https://en.wikipedia.org/wiki/Logogram][logographic]]. 
Katakana, which is more angular in appearance, is used predominantly for 
foreign words introduced to the Japanese language.

\\
* Examples

: hiragana *ひらがな* (hiragana)  
: anata *あなた* (you)  
: watashi *わたし* (I)   

\\

Look confusing? Let's break it down.

: hi
: ひ
: ra
: ら  
: ga
: が  
: na
: な  
\\
Modern Hiragana consists of 46 phonetic characters. If you try to pronounce words written 
in romanji while reading their hiragana you can see that each syllable matches a hiragana 
character.
\\

: watashi no namae wa Stephen desu  
: わ た し の なまえ わ Stephen です
: my name is Stephen

\\
* Learning

Since hiragana is a phonetic system it is relatively easy, and fun, to learn. Many of the 
characters are re-used to produce a slightly different sound through the use of the diacritic 
signs [[https://en.wikipedia.org/wiki/Ten-ten][ten-ten]] (dakuten), which resemble a 
quotation mark, and  maru (handakuten), which resemble a circle. I suggest using the free ebook 
[[http://cdn.textfugu.com/downloads/ebooks/hiragana42.zip][Hiragana42]] or the 'Memorizing the 
Hiragana' [[https://en.wikibooks.org/wiki/Memorizing_the_Hiragana][wikibook]] to learn hiragana. 
Both of these utilise mnemonics which makes recalling each character a lot easier. I found it 
useful to then use the pronunciation tests in the application
[[http://www.humanjapanese.com][Human Japanese]] 
to test what I have already learnt while learning the proper pronunciation. There is a useful 
poem called Iroha (いろは) that I have added to the appendix of this page. 
This is an old Japanese poem that is valuable for studying hiragana as it contains all of the 
hiragana characters apart from ん (n).

A small tsu character (*っ*) is used to indicate that the consonant in the next character should be said twice.\\

: nippon にっぽん (Japan)
: ni に
: small tsu っ
: po ぽ
: n ん_

(Did you spot the [[https://www.youtube.com/watch?v=2XID_W4neJo][maru]]?)

\\
If にっぽん did not contain the small tsu character (っ) it would
spell nipon (にぽん) which is not a word in Japanese. When the small
tsu (っ) is used it breaks up the sound of the word between the double
consonant. Nippon (にっぽん) should be pronounced Nip-pon. The small
tsu (っ) isn’t the only small character that is used in hiragana. To
add to the confusion a small ya (ゃ), yu (ゅ) and yo (ょ) can be
placed after another character to create a ‘y vowel sound’.\\


: hi (*ひ*)  +  ya (*ゃ*)  = t hya (*ひゃ*)
: ri (*り*)  +  ya (*ゃ*)  =  rya (*りゃ*)
: shi (*し*)  +  ya (*ゃ*)  =  sha (*しゃ*)

\\
* Next   

Once I had learnt these characters it was nice to 
go back to Japanese words I had already encountered and convert them from romanji to hiragana. 
At this point I am still only able to read a small amount of Japanese writing due to the heavy 
use of the other writing systems. Hiragana is sometimes written around kanji, called 
[[https://en.wikipedia.org/wiki/Furigana][furigana]], to aid pronunciation but this 
is generally only used for uncommon kanji. After the other main syllabary katakana 
(*カタカナ*) the real test will be kanji (*漢字*).

\\



